### ISSUE TITLE
It's seem no working?

### ISSUE THREAD

**Issue by 625781186** [gleb-sevruk/pycrunch-engine#11]
ENV:
    pycharm 2019.1.2
    pycrunch-live-testing v0.9.0-SNAPSHOT

There are no running `green dots`.

![image](https://user-images.githubusercontent.com/30521429/73733206-7f8ecf00-4776-11ea-9a78-157887774c3f.png)

**Comment by gleb-britecore** [comment]
It seems like your test is not discovered.

I also notice that you might accidentally filter test from the list.

Can you include all tests (success, failing, pending, pinned), and manually run it for the first time?

markers will not show automatically until you execute some test manually

**Comment by gleb-britecore** [comment]
If this will not work, let me know, so I can post further diagnostic steps

**Comment by 625781186** [comment]
It still not work.

![image](https://user-images.githubusercontent.com/30521429/73734628-e44b2900-4778-11ea-82f2-cc3a96fdf19d.png)

**Comment by 625781186** [comment]
I rename `test` fold to `tests` , it's work.

**Comment by gleb-britecore** [comment]
Thanks for letting know about the fix!

Keep in mind that I'm not using pytest discovery mechanism. Pytest is based on parsing AST for source files and it is a bit different. 

For PyCrunch, test file should be importable (e.g. contain __init__.py). Also, I believe it is a bug in the discovery engine, and I will fix it sometime in the future. As I believe both `test` and `tests` are valid names.

Also, I did a small investigation and there were no issues using `test` folder name:
![image](https://user-images.githubusercontent.com/29545691/73737668-c0252300-474b-11ea-9e72-de39d43f63ff.png)

Sometimes I had this previously when there are a lot of packages installed in the virtual environment, and they have conflicting names

**Comment by 625781186** [comment]
@gleb-britecore 

![image](https://user-images.githubusercontent.com/30521429/73746409-161bba00-4790-11ea-8e39-6da7209d85e5.png)

You are right .
It has nothing to do with the folder name, 
so I don't know what happened.
