### ISSUE TITLE
PyCharm Plugin: Support 2024.1

### ISSUE THREAD

**Issue by dkMikLev** [gleb-sevruk/pycrunch-engine#124]
PyCharm 2024.1 requires plugin update :(
 
<img width="497" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/84900760/b6b2c5f3-8eaa-4d27-8eee-a5e08fa6052e">

**Comment by gleb-sevruk** [comment]
Hello, update submitted to jetbrains verification. In the meantime you can install the new version from disk

<img width="710" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/3c26f39e-3b58-4b9c-8227-bdc8f8137536">

[pycrunch-intellij-connector-1.6.3.zip](https://github.com/gleb-sevruk/pycrunch-engine/files/14889335/pycrunch-intellij-connector-1.6.3.zip)

**Comment by gleb-sevruk** [comment]
please use this distribution for 2024.1, not the previous archive I posted :) 

[pycrunch-intellij-connector-1.6.3-github.zip](https://github.com/gleb-sevruk/pycrunch-engine/files/14889473/pycrunch-intellij-connector-1.6.3-github.zip)

**Comment by gleb-sevruk** [comment]
note: jetbrains sdk changged imports, so it Is harder to do backward and forward compatible releases
<img width="787" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/7a7498da-1a11-4f65-b6f9-2af86752ef69">

**Comment by dkMikLev** [comment]
Thank you so much!
This really is an amazing project.
