### ISSUE TITLE
Q: no nose(tests) support is planned, correct?

### ISSUE THREAD

**Issue by yarikoptic** [gleb-sevruk/pycrunch-engine#27]
I know that `nose` is slowly going away, but we still use it in some projects, so I just wondered.

**Comment by gleb-sevruk** [comment]
Yeah.

I don't think I can invest time into it. 

But you can try writing plugin for it, that should be pretty straightforward:
https://github.com/gleb-sevruk/pycrunch-engine/tree/master/pycrunch/plugins 

This may be as simple as running `pytest.main` but for `nose`

**Comment by gleb-sevruk** [comment]
Not planned officially for now
