### ISSUE TITLE
Enhancement - IJ plugin to initialize on a predefined port

### ISSUE THREAD

**Issue by valeedmalik** [gleb-sevruk/pycrunch-engine#37]
I might be missing something however every time I trigger pycrunch-engine via IJ, it will start it on a random port. I am working with Django out of a container where I need to specify port to open on the container to connect to the engine. Currently I'm making an exec call into the container and starting pycrunch-engine on 5000 and have my container open at the same. 

Would you know of a work around for this? Would like to utilize start/stop of engine from IJ.

**Comment by gleb-britecore** [comment]
2 possible workarounds to this:

1. You can try to start the engine manually via command-line, and connecting to a custom process:
![image](https://user-images.githubusercontent.com/29545691/103308712-c1260980-4a1b-11eb-857a-e49fe5c130d2.png)

2. Also the port is randomized at the first run will stay the same during the entire IntelliJ session, so you can re-setup container once per day 😄

**Comment by valeedmalik** [comment]
Yep have been operating via method 2. Was just hoping for a more direct approach!
