### ISSUE TITLE
pytest.mark.parametrized if one case fails the test still passes

### ISSUE THREAD

**Issue by jrote1** [gleb-sevruk/pycrunch-engine#4]
```
@pytest.mark.parametrize(
    "key,sub_key,value",
    [
        ("DB.HOST", "HOST", "hostname"),
        ("DB.USER", "USER", "admin"),
    ],
)
def test_can_load_nested_config_value(key, sub_key, value):
    os.environ[key] = value

    config = Config().use_environment_config()
    assert config["DB"][sub_key] == value
```

![image](https://user-images.githubusercontent.com/4202486/65866725-37e1dc00-e36d-11e9-8715-8dadf4f5fe46.png)

**Comment by gleb-sevruk** [comment]
I remember doing some work regarding this, but from the code I now see, it is quite not correct
https://github.com/gleb-sevruk/pycrunch-engine/blob/master/pycrunch/plugins/django_support/django_runner_engine.py#L44
https://github.com/gleb-sevruk/pycrunch-engine/blob/master/pycrunch/plugins/pytest_support/interception_plugin.py#L61


You can apply this fix and let me know if this works as expected

https://github.com/gleb-sevruk/pycrunch-engine/pull/5


The bigger problem for me regarding this is that I wanted to display coverage per each parametrized test separately, but this may be daunting in the current codebase

more generalized example (without dependencies)
```
import pytest


@pytest.mark.parametrize(
    "a,b,c",
    [
        (1, 2, 3),
        (2, 2, 5),
    ],
)
def test_sum_parametrized(a, b, c):
    assert a + b == c
```

**Comment by gleb-sevruk** [comment]
I updated pip package to 0.7.1 with a fix.
`pip install pycrunch-engine==0.7.1`

Let me know if this helps

**Comment by jrote1** [comment]
@gleb-sevruk that fixes the issue, thanks for really quick fix
