### ISSUE TITLE
unittest framework

### ISSUE THREAD

**Issue by jrote1** [gleb-sevruk/pycrunch-engine#6]
Is there any plans to support the unittest framework?

**Comment by gleb-sevruk** [comment]
I'm not a big user of `Unittest`. 

In most cases, I found that pytest can be interchangeable, with existing tests.
For instance, I'm using pytest under the hood to run Django tests.

Furthermore, current code supports unittest test cases with setUp/tearDown methods.
https://github.com/gleb-sevruk/pycrunch-engine/blob/master/pycrunch/discovery/simple.py#L140
![image](https://user-images.githubusercontent.com/609801/65880346-55796a80-e39a-11e9-8149-7a4bcbb816ba.png)


Can you provide more details regarding your use case, maybe with some demo code?
