### ISSUE TITLE
async test for method in class not discovered.

### ISSUE THREAD

**Issue by vegaroy13** [gleb-sevruk/pycrunch-engine#62]
Hi, I wonder if you can help me in this situation.

I want to have a class and do async tests. If I run my tests with pytest in the command line and also by using unittest, this code runs, but, pycrunch seems not to discover (or maybe my error is other).

In this image, if the word 'async' is *ommited*, the test is shown and executed (incorrectly)

![pycrunch](https://user-images.githubusercontent.com/1682324/147783149-67bbc34e-e6ff-40e1-8dcd-1e03e80d3467.png)

If I make it work, as an async test, the test is not discovered:

![pycrunch2](https://user-images.githubusercontent.com/1682324/147783421-ac70860d-b1dc-4367-99df-be92b422f8c9.png)

I also tryed the recommended code in:
https://github.com/gleb-sevruk/pycrunch-engine/issues/52

but is not discovered, or maybe I need some special config.

![pycrunch3](https://user-images.githubusercontent.com/1682324/147783477-380f74ad-f0c4-4215-a817-0ec27c9ea38b.png)

Thank you very much in advanced.
(BTW, very cool tool!!!)

**Comment by AbstractiveNord** [comment]
+1

**Comment by gleb-sevruk** [comment]
That is now fixed thanks to https://github.com/gleb-sevruk/pycrunch-engine/pull/100 and https://github.com/gleb-sevruk/pycrunch-engine/pull/101

**Comment by vegaroy13** [comment]
Oh Thank You. Just update to back-front last updates (1.6.1) and works over python 3.10. Previous versions of python will fail due to syntax updated code not supported.
