### ISSUE TITLE
doesn't find all tests

### ISSUE THREAD

**Issue by atjtest** [gleb-sevruk/pycrunch-engine#75]
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022

pycrunch-engine==1.4

The tests folder structure is as below:
tests/
  test_1.py
  test_2.py
  util/
     test_util1.py
     test_util2.py

The pycrunch finds the test in tests.util.test_util1.py and tests.util.test_util2.py, but it doesn't find tests in tests.test_1.py and tests.test_2.py. 
There is no error in the run console.
There is no exclusions in .pycrunch-config.yaml.

Anyone has insight why it doesn't find any tests in the root of tests folder?

**Comment by gleb-sevruk** [comment]
Can you try to add `__init__.py` into the `tests` folder and see if that helps?

**Comment by gleb-sevruk** [comment]
Please publish a minimal reproducible example. Maybe there is some nesting involved or async functions?

**Comment by gleb-sevruk** [comment]
Closing as inactive. Feel free to reopen and publish example.
