### ISSUE TITLE
Pycharm: "Tests covering this line" wrong sorting

### ISSUE THREAD

**Issue by antondeliverect** [gleb-sevruk/pycrunch-engine#92]
Hello;) First of all, it's a really great module i really like it. 

I wanted to share with you small issue i've came across: `Tests covering this line` is unsorted,
<img width="982" alt="Screenshot 2023-04-19 at 15 40 39" src="https://user-images.githubusercontent.com/103994541/233095471-3712ff40-3804-4019-a14a-6e211e66fd9f.png">

it's hard to look through this list when there's a lot of tests covering a single line and they're shuffled(i.e. no alphabetical sorting)._.

**Comment by gleb-sevruk** [comment]
Thanks for report, this looks like a easy fix that I will address in the next update

**Comment by gleb-sevruk** [comment]
Before (1.5.1):
<img width="331" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/63c5fd13-278a-4332-bf10-3775ba5a555f">

After (1.5.2)
![telegram-cloud-photo-size-2-5400236074489466208-x](https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/f96c1aa2-88c9-42b8-84fb-882cdf9b4c47)


release pending

**Comment by gleb-sevruk** [comment]
Before  (1.5.1)
<img width="334" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/b48df712-5ebb-44b6-9838-019a51f27cbd">

After (1.5.2):
<img width="332" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/23a82edd-b895-475f-ba47-61e652f8116f">

Release pending...

**Comment by gleb-sevruk** [comment]
Todo: retest on 1.6.0;

**Comment by gleb-sevruk** [comment]
<img width="672" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/3f02ca87-4f32-4ed6-a2a3-de8fc717d1f4">
verified on 1.6.3, closing
